#! Tạo virtual server trong Nginx
server {
    listen 80; # Port
    server_name localhost; #Domain

    # Frontend SPA
    location / { 
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Static cache (Regex xử lý file tĩnh, lưu cache trong 30d)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|ttf|svg)$ {
        root /usr/share/nginx/html;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # API
    location /api/ {
        proxy_pass http://api:8080/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    #OCR
    location /ocr/ {
        proxy_pass http://ocr:8002/;
    }

    #ML
    location /ml/ {
        proxy_pass http://ml:8001/;
    }
    # Error
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}