version: "3.9"

# Khai báo container
services:
  # ! Database
  db: # Domain
    image: postgres:15 #Image gốc
    container_name: expense-db # Tên container
    restart: always #Container crash => tự restart
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: #<Host>:<Container>
      - "5432:5432"
    volumes: #Persist dữ liệu DB
      - db_data:/var/lib/postgresql/data
    healthcheck: #Kiểm tra DB ready? (mỗi 5s, timeout 5s, thử tối đa 5l)
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  #! Backend
  api:
    build: ./ExpenseTrackerAPI
    container_name: expense-api
    depends_on:
      db:
        condition: service_healthy
      ocr:
        condition: service_started
      ml:
        condition: service_started
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      OCR_URL: http://ocr:8002
      ML_URL: http://ml:8001

  #! OCR
  ocr:
    build: ./OCRServer
    container_name: ocr-service
    environment:
      - OMP_NUM_THREADS=2
      - MKL_NUM_THREADS=2
      - OPENBLAS_NUM_THREADS=2
      - NUMEXPR_NUM_THREADS=2
  #! ML
  ml:
    build: ./MLServer
    container_name: ml-service

  #! Frontend
  frontend:
    build: ./expense-tracker-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  db_data:
