CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" character varying(150) NOT NULL,
        "PasswordHash" text NOT NULL,
        "FullName" character varying(100) NOT NULL,
        "Role" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "Accounts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Type" text NOT NULL,
        "Balance" numeric(18,2) NOT NULL,
        "Currency" text NOT NULL,
        "Color" text,
        "Logo" text,
        "UserId" integer NOT NULL,
        CONSTRAINT "PK_Accounts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Accounts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "Categories" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Icon" character varying(50) NOT NULL,
        "Color" character varying(20) NOT NULL,
        "UserId" integer,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Categories_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "Loans" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "CounterPartyName" character varying(255) NOT NULL,
        "PrincipalAmount" numeric(18,2) NOT NULL,
        "RemainingAmount" numeric(18,2) NOT NULL,
        "InterestRate" numeric(5,2) NOT NULL,
        "InterestUnit" character varying(50) NOT NULL,
        "StartDate" timestamp with time zone NOT NULL,
        "DueDate" timestamp with time zone,
        "Note" text NOT NULL,
        "IsCompleted" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Loans" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Loans_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "UserSettings" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "DefaultCurrency" character varying(3) NOT NULL,
        "Language" character varying(10) NOT NULL,
        "Theme" character varying(20) NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserSettings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserSettings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "RepaymentSchedules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Period" integer NOT NULL,
        "PrincipalAmount" numeric(18,2) NOT NULL,
        "InterestAmount" numeric(18,2) NOT NULL,
        "TotalAmount" numeric(18,2) NOT NULL,
        "RemainingBalance" numeric(18,2) NOT NULL,
        "DueDate" timestamp with time zone NOT NULL,
        "IsPaid" boolean NOT NULL,
        "PaidDate" timestamp with time zone,
        "LoanId" integer NOT NULL,
        CONSTRAINT "PK_RepaymentSchedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RepaymentSchedules_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE TABLE "Transactions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Amount" numeric(18,2) NOT NULL,
        "ConvertedAmount" numeric(18,2),
        "BalanceBefore" numeric(18,2) NOT NULL,
        "BalanceAfter" numeric(18,2) NOT NULL,
        "Note" text NOT NULL,
        "TransactionDate" timestamp with time zone NOT NULL,
        "ImageUrl" text NOT NULL,
        "Type" character varying(20) NOT NULL,
        "UserId" integer NOT NULL,
        "FromAccountId" integer,
        "ToAccountId" integer,
        "CategoryId" integer,
        "LoanId" integer,
        CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Transactions_Accounts_FromAccountId" FOREIGN KEY ("FromAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Transactions_Accounts_ToAccountId" FOREIGN KEY ("ToAccountId") REFERENCES "Accounts" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Transactions_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id"),
        CONSTRAINT "FK_Transactions_Loans_LoanId" FOREIGN KEY ("LoanId") REFERENCES "Loans" ("Id"),
        CONSTRAINT "FK_Transactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    INSERT INTO "Categories" ("Id", "Color", "Icon", "Name", "UserId")
    VALUES (1, '#FF5733', 'Utensils', 'Ăn uống', NULL);
    INSERT INTO "Categories" ("Id", "Color", "Icon", "Name", "UserId")
    VALUES (2, '#33FF57', 'Car', 'Di chuyển', NULL);
    INSERT INTO "Categories" ("Id", "Color", "Icon", "Name", "UserId")
    VALUES (3, '#3357FF', 'ShoppingBag', 'Mua sắm', NULL);
    INSERT INTO "Categories" ("Id", "Color", "Icon", "Name", "UserId")
    VALUES (4, '#22c55e', 'Banknote', 'Lương', NULL);
    INSERT INTO "Categories" ("Id", "Color", "Icon", "Name", "UserId")
    VALUES (5, '#2563eb', 'Landmark', 'Vay nợ', NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Accounts_UserId" ON "Accounts" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Categories_UserId" ON "Categories" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Loans_UserId" ON "Loans" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_RepaymentSchedules_LoanId" ON "RepaymentSchedules" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Transactions_CategoryId" ON "Transactions" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Transactions_FromAccountId" ON "Transactions" ("FromAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Transactions_LoanId" ON "Transactions" ("LoanId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Transactions_ToAccountId" ON "Transactions" ("ToAccountId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE INDEX "IX_Transactions_UserId" ON "Transactions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    CREATE UNIQUE INDEX "IX_UserSettings_UserId" ON "UserSettings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260402101231_InitialDB') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260402101231_InitialDB', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403033058_CurrencyTransaction') THEN
    ALTER TABLE "Transactions" ADD "Currency" character varying(5) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260403033058_CurrencyTransaction') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260403033058_CurrencyTransaction', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412082916_Databasev2') THEN
    CREATE TABLE "Budgets" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "CategoryId" integer NOT NULL,
        "Month" text NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "Currency" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Budgets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Budgets_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412082916_Databasev2') THEN
    CREATE INDEX "IX_Budgets_CategoryId" ON "Budgets" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412082916_Databasev2') THEN
    CREATE UNIQUE INDEX "IX_Budgets_UserId_CategoryId_Month" ON "Budgets" ("UserId", "CategoryId", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412082916_Databasev2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260412082916_Databasev2', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413201814_Databasev3') THEN
    ALTER TABLE "Transactions" ADD "ConvertedCurrency" character varying(5);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260413201814_Databasev3') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260413201814_Databasev3', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417193153_Databasev4') THEN
    ALTER TABLE "Loans" ADD "Currency" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260417193153_Databasev4') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260417193153_Databasev4', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418145717_Databasev5') THEN
    ALTER TABLE "Loans" ADD "IsLending" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260418145717_Databasev5') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260418145717_Databasev5', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419161040_Databasev6') THEN
    ALTER TABLE "Users" ADD "LastLoginAt" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419161040_Databasev6') THEN
    CREATE TABLE "AuditLog" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ActorUserId" integer,
        "Action" text NOT NULL,
        "EntityType" text NOT NULL,
        "EntityId" text NOT NULL,
        "Details" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UserId" integer,
        CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLog_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419161040_Databasev6') THEN
    CREATE INDEX "IX_AuditLog_UserId" ON "AuditLog" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419161040_Databasev6') THEN
    ALTER TABLE "Budgets" ADD CONSTRAINT "FK_Budgets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419161040_Databasev6') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419161040_Databasev6', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424155638_AddPersonalCategoryRules') THEN
    CREATE TABLE "PersonalCategoryRules" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Keyword" character varying(100) NOT NULL,
        "Type" character varying(20) NOT NULL,
        "CategoryId" integer NOT NULL,
        "Count" integer NOT NULL,
        "LastUsedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PersonalCategoryRules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PersonalCategoryRules_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PersonalCategoryRules_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424155638_AddPersonalCategoryRules') THEN
    CREATE INDEX "IX_PersonalCategoryRules_CategoryId" ON "PersonalCategoryRules" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424155638_AddPersonalCategoryRules') THEN
    CREATE UNIQUE INDEX "IX_PersonalCategoryRules_UserId_Type_Keyword_CategoryId" ON "PersonalCategoryRules" ("UserId", "Type", "Keyword", "CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424155638_AddPersonalCategoryRules') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260424155638_AddPersonalCategoryRules', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    ALTER TABLE "Loans" ADD "IsRecurringReminder" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    ALTER TABLE "Loans" ADD "NextReminderDate" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    ALTER TABLE "Loans" ADD "ReminderBeforeDays" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    ALTER TABLE "Loans" ADD "ReminderFrequency" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    UPDATE "Categories" SET "Icon" = 'Gamepad2', "Name" = 'Giải trí'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    UPDATE "Categories" SET "Icon" = 'Receipt', "Name" = 'Hoá đơn'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426162524_DBv7') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426162524_DBv7', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426173559_AddPushSubscriptions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426173559_AddPushSubscriptions', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426180237_AddPushSubscription') THEN
    CREATE TABLE "Notifications" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Title" text NOT NULL,
        "Message" text NOT NULL,
        "Type" text NOT NULL,
        "IsRead" boolean NOT NULL,
        "RedirectUrl" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426180237_AddPushSubscription') THEN
    CREATE TABLE "PushSubscriptions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" integer NOT NULL,
        "Endpoint" text NOT NULL,
        "P256dh" text NOT NULL,
        "Auth" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PushSubscriptions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PushSubscriptions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426180237_AddPushSubscription') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426180237_AddPushSubscription') THEN
    CREATE INDEX "IX_PushSubscriptions_UserId" ON "PushSubscriptions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260426180237_AddPushSubscription') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260426180237_AddPushSubscription', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428081113_AddTransactionImages') THEN
    ALTER TABLE "Transactions" DROP COLUMN "ImageUrl";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428081113_AddTransactionImages') THEN
    CREATE TABLE "TransactionImages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TransactionId" integer NOT NULL,
        "ImageUrl" character varying(500) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_TransactionImages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TransactionImages_Transactions_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES "Transactions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428081113_AddTransactionImages') THEN
    CREATE INDEX "IX_TransactionImages_TransactionId" ON "TransactionImages" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428081113_AddTransactionImages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428081113_AddTransactionImages', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507024755_AddReceiptTable') THEN
    CREATE TABLE "ReceiptJobResults" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "JobId" text NOT NULL,
        "UserId" integer NOT NULL,
        "Status" text NOT NULL,
        "Error" text,
        "CreatedAt" timestamp with time zone NOT NULL,
        "Data" jsonb,
        CONSTRAINT "PK_ReceiptJobResults" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507024755_AddReceiptTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507024755_AddReceiptTable', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514015723_AddPaidAmount') THEN
    ALTER TABLE "RepaymentSchedules" ADD "PaidInterestAmount" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514015723_AddPaidAmount') THEN
    ALTER TABLE "RepaymentSchedules" ADD "PaidPrincipalAmount" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514015723_AddPaidAmount') THEN
    ALTER TABLE "RepaymentSchedules" ADD "PaidTotalAmount" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260514015723_AddPaidAmount') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260514015723_AddPaidAmount', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    ALTER TABLE "Categories" ADD "Description" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    ALTER TABLE "Categories" ADD "Keywords" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    UPDATE "Categories" SET "Description" = NULL, "Keywords" = NULL
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    UPDATE "Categories" SET "Description" = NULL, "Keywords" = NULL
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    UPDATE "Categories" SET "Description" = NULL, "Keywords" = NULL
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    UPDATE "Categories" SET "Description" = NULL, "Keywords" = NULL
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    UPDATE "Categories" SET "Description" = NULL, "Keywords" = NULL
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260526124849_UpdateCategory') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260526124849_UpdateCategory', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611035738_AddInterestCalculationTypeToLoan') THEN
    ALTER TABLE "Loans" ADD "InterestCalculationType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611035738_AddInterestCalculationTypeToLoan') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611035738_AddInterestCalculationTypeToLoan', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
        ALTER TABLE "Transactions"
        ALTER COLUMN "Type" DROP DEFAULT;

        ALTER TABLE "Transactions"
        ALTER COLUMN "Type" TYPE integer
        USING CASE lower("Type"::text)
            WHEN 'expense' THEN 1
            WHEN 'income' THEN 2
            WHEN 'transfer' THEN 3
            WHEN 'borrow' THEN 4
            WHEN 'lend' THEN 5

            WHEN 'chi' THEN 1
            WHEN 'thu' THEN 2
            WHEN 'chuyen_khoan' THEN 3
            WHEN 'vay' THEN 4
            WHEN 'cho_vay' THEN 5

            WHEN '10' THEN 4
            WHEN '11' THEN 5

            ELSE
                CASE
                    WHEN "Type"::text ~ '^[0-9]+$' THEN "Type"::integer
                    ELSE 1
                END
        END;

        ALTER TABLE "Transactions"
        ALTER COLUMN "Type" SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
        ALTER TABLE "PersonalCategoryRules"
        ALTER COLUMN "Type" DROP DEFAULT;

        ALTER TABLE "PersonalCategoryRules"
        ALTER COLUMN "Type" TYPE integer
        USING CASE lower("Type"::text)
            WHEN 'expense' THEN 1
            WHEN 'income' THEN 2
            WHEN 'transfer' THEN 3
            WHEN 'borrow' THEN 4
            WHEN 'lend' THEN 5

            WHEN 'chi' THEN 1
            WHEN 'thu' THEN 2
            WHEN 'chuyen_khoan' THEN 3
            WHEN 'vay' THEN 4
            WHEN 'cho_vay' THEN 5

            WHEN '10' THEN 4
            WHEN '11' THEN 5

            ELSE
                CASE
                    WHEN "Type"::text ~ '^[0-9]+$' THEN "Type"::integer
                    ELSE 1
                END
        END;

        ALTER TABLE "PersonalCategoryRules"
        ALTER COLUMN "Type" SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
        ALTER TABLE "Loans"
        ALTER COLUMN "ReminderFrequency" DROP DEFAULT;

        ALTER TABLE "Loans"
        ALTER COLUMN "ReminderFrequency" TYPE integer
        USING CASE lower("ReminderFrequency"::text)
            WHEN 'daily' THEN 0
            WHEN 'weekly' THEN 1
            WHEN 'monthly' THEN 2

            WHEN 'day' THEN 0
            WHEN 'week' THEN 1
            WHEN 'month' THEN 2

            ELSE
                CASE
                    WHEN "ReminderFrequency"::text ~ '^[0-9]+$' THEN "ReminderFrequency"::integer
                    ELSE 2
                END
        END;

        ALTER TABLE "Loans"
        ALTER COLUMN "ReminderFrequency" SET DEFAULT 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
        ALTER TABLE "Loans"
        ALTER COLUMN "InterestUnit" DROP DEFAULT;

        ALTER TABLE "Loans"
        ALTER COLUMN "InterestUnit" TYPE integer
        USING CASE lower("InterestUnit"::text)
            WHEN 'percent_per_month' THEN 1
            WHEN 'percent_per_year' THEN 2
            WHEN 'percentpermonth' THEN 1
            WHEN 'percentperyear' THEN 2
            WHEN 'month' THEN 1
            WHEN 'year' THEN 2

            ELSE
                CASE
                    WHEN "InterestUnit"::text ~ '^[0-9]+$' THEN "InterestUnit"::integer
                    ELSE 1
                END
        END;

        ALTER TABLE "Loans"
        ALTER COLUMN "InterestUnit" SET DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
    ALTER TABLE "Loans" ADD "Duration" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
    ALTER TABLE "Loans" ADD "DurationUnit" integer NOT NULL DEFAULT 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260611065556_Enum') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260611065556_Enum', '8.0.8');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    DROP INDEX "IX_Notifications_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Notifications" ALTER COLUMN "Type" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Notifications" ALTER COLUMN "Title" TYPE character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Notifications" ALTER COLUMN "RedirectUrl" TYPE character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Notifications" ALTER COLUMN "Message" TYPE character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Notifications" ADD "ReferenceKey" character varying(200);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Budgets" ALTER COLUMN "Month" TYPE character varying(7);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Budgets" ALTER COLUMN "Currency" TYPE character varying(5);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Budgets" ALTER COLUMN "Amount" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    ALTER TABLE "Budgets" ADD "Spent" numeric(18,2) NOT NULL DEFAULT 0.0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    CREATE UNIQUE INDEX "IX_Notifications_UserId_Type_ReferenceKey" ON "Notifications" ("UserId", "Type", "ReferenceKey") WHERE "ReferenceKey" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260615190533_AddReferenceKeyToNotifications') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260615190533_AddReferenceKeyToNotifications', '8.0.8');
    END IF;
END $EF$;
COMMIT;

